#!/usr/bin/env bash
# Redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=GM-e46xdcUo&list=LL&index=10 permanent;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
