#!/usr/bin/env bash
# Redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /usr/share/nginx/html;
	index index.html index.htm
	location /redirect_me {
		return 301 
		https://www.youtube.com/watch?v=GM-e46xdcUo&list=LL&index=9;
	}
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
