#!/usr/bin/env bash
# Custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect-me https://www.youtube.com/watch?v=GM-e46xdcUo&list=LL&index=10;\n' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/new.html
sudo sed -i '/listen 80 default_server/a error_page 404 /new.html;' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
