#!/usr/bin/env bash
# Script that prints numbers 1-20 with special phrases on certain numbers

i=0

while ((i<21));do
	case $i in
		4)
		    echo "$i"
		    echo "bad luck from China";;
		9)
		    echo "$i"
		    echo "bad luck from Japan";;
		17)
		    echo "$i"
		    echo "bad luck from Italy";;
		*)
		    echo "$i"
	esac
	((i++))
done
